services:
  email-template:
    image: optiwariindia/email-template:latest
    container_name: email-template
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      TZ: ${TZ}
    volumes:
      - ${TEMPLATE_DIR}:/app/templates
