services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP}
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE}
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
