services:
  db:
    image: mongo:latest
    environment:
      - TZ=${TZ}
    volumes:
      - ./data/db:/data/db
    networks:
      - attendance
    restart: unless-stopped
  attendance:
    image: registry.sampledge.com/hrms/attendance:1.0.0
    environment:
      - TZ=${TZ}
      - PORT=${PORT}
      - DB=mongodb://db/${DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - attendance
      - publicweb
    restart: unless-stopped
    volumes:
      - ./creds:/app/creds
networks:
  publicweb:
    external: true
  attendance:    