services:
  whatsmeow:
    image: optiwariindia/whatsmeow:latest
    container_name: whatsmeow
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      TZ: ${TZ}
    volumes:
      - ${SESSION_PATH}:/app/session
